<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita55c7485869a86ae5242f8ae5fb5d265
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Twilio\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Twilio\\' => 
        array (
            0 => __DIR__ . '/..' . '/twilio/sdk/src/Twilio',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita55c7485869a86ae5242f8ae5fb5d265::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita55c7485869a86ae5242f8ae5fb5d265::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
